player-defaults:
  damage: [1,2]
  rangedDamage: [1,2]
  armor: 1
  critical: 0.025
  criticalDamage: 1.2
  block: 0.015
  parry: 0.015
  dodge: 0.015
  penetrate: 0.015
  attributes:
      strength: 1
      vitality: 1
      agility: 1
      tenacity: 1
      intellect: 1
      spirit: 5